name: feddag_test_env
channels:
  - pytorch
dependencies:
  - python=3.7
  - pandas=1.3.5
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - pytorch=1.2.0
  - torchvision=0.4.0
  - cudatoolkit=10.0
  - networkx=2.6.3
  - protobuf=3.19
  - pip
  - pip:
    - tensorflow-gpu==1.15